---

- hosts: webservers
  user: someuser
  sudo: True

  vars:
    repository_basedir: ..
    git_username: Some User
    git_usermail: someuser@somedomain.com

  tasks:
    # Install Git
    - include: {{ repository_basedir }}/git/tasks/setup.yml

