---

- hosts: webservers
  user: vagrant
  sudo: True

  vars_files:
  - {{ repository_basedir }}/graphite/vars/main.yml

  vars:
    repository_basedir: ..
    graphite_user: vagrant
    graphite_storage:
    - title: 'cpu_load'
      pattern: '^servers\.'
      retentions: '60s:1d'

  tasks:
  - include: {{ repository_basedir }}/graphite/tasks/setup.yml
