---
# File: module_disable.yml
# Part: Apache
#         
# Description: Disable an apache module Apache server
#
# Parameters:
# - {{ module }}: the module name (ex. rewrite)
#
# Dependencies ([part:]type:filename):
# - handlers:handlers.yml
#
# OS: Ubuntu

- name: Apache | Disable module | Disable {{ module }}
  command: a2dismod {{ module }} removes=/etc/apache2/mods-enabled/{{ module }}.load
  notify: 
  - apache-restart

