---
# File: vhost_add.yml
# Part: Apache
#
# Description: Create a new virtual host
#
# Parameters:
# - {{ docroot }} : absolute docroot path
# - {{ vhost }} : virtualhost name
# - {{ create_docroot }} : create the docroot directory in the filesystem (if it doesn't exist) and push a default index file.
# - {{ port }} : 80 by default
# - {{ interfaces }} : * by default
#
# Dependencies-internal ([part:]type:filename):
# - handlers:handlers.yml
#
# OS familly: Ubuntu

- name: Apache | Virtualhost add | Create document root at {{ docroot }}
  file:
    path={{ docroot }}
    state=directory
    owner={{ apache_user }} group={{ apache_group }} mode=0755
  when: $create_docroot == 1

- name: Apache | Virtualhost add | Push virtualhost configuration template
  sudo: yes
  template:
    src={{ repository_basedir }}/apache/templates/virtualhost.j2
    dest=/etc/apache2/sites-available/{{ vhost }}

- name: Apache | Virtualhost add | Activate virtual host {{ vhost }}
  sudo: yes
  command: /usr/sbin/a2ensite {{ vhost }} creates=/etc/apache2/sites-enabled/{{ vhost }}
  notify:
  - apache-reload
