---
# File: setup.yml
# Part: Project
#
# Description: Create a site root, vhost and then clone a project repository
#
# Parameters:
# - project_name: (string) The base project name
# - project_url: (string) The git clone URL
# - project_host: (string) The hosts entry and server name to use
# - 
#
# Dependencies ([part:]type:filename):
# - vars:main.yml
# - handlers:handlers.yml
#
# OS familly: Ubuntu

- name: Create /var/www/sites/{{ project_name }}
  action: file dest=/var/www/sites/{{ project_name }} state=directory mode=0775
  
- include: "{{ repository_basedir }}/apache/tasks/vhost_add.yml docroot=/var/www/sites/{{ project_name}}/web vhost={{ project_host }} create_docroot=false"
- include: "{{ repository_basedir }}/apache/tasks/vhost_ssl_add.yml docroot=/var/www/sites/{{ project_name}}/web vhost={{ project_host }}-ssl create_docroot=false port=443"

- name: Set hosts entry
  sudo: yes
  host: ip=127.0.0.1 hostname=localhost aliases={{ project_host }}

- name: Clone project repository
  git: repo={{ project_url }} dest=/var/www/sites/{{ project_name }} version=develop
