---
- hosts: hosts
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ../../ansible-repository

  tasks:
    - include: {{ repository_basedir }}/nginx/tasks/setup.yml
    - include: {{ repository_basedir }}/nginx/tasks/vhost_add.yml create_root=true name=domain.com root=/vagrant/www type=html

  handlers:
    - include: {{ repository_basedir }}/nginx/handlers/handlers.yml
