---
# Part: PHP
# File: pecl.yml
#
# Description: Manage Pecl package installations
#   Supposes the config template file php/templates/{{ package }}.ini.j2 exists
#
# Parameters:
# - {{ package }} : the package to install
# - {{ version }} : stable, beta, alpha
# - {{ stdin }} : input to send to the install process.
#
# Dependencies ([part:]type:filename):
# - tasks:setup.yml
#
# OS familly: Ubuntu (>= 12.04)

- name: PHP | PECL | Insure PHP development packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-dev
    - php-pear

- name: PHP | PECL | Install {{ package }}-{{ version }}
  shell: echo {{ stdin }} | pecl install {{ package }}-{{ version }}
  ignore_errors: yes

- name: PHP | PECL | Set {{ package }} config (Ubuntu == 12.04)
  template:
    src={{ repository_basedir }}/php/templates/{{ package }}.ini.j2
    dest=/etc/php5/conf.d/{{ package }}.ini
    owner=root group=root mode=0644
  when: ${ansible_lsb.release} == "12.04"

- name: PHP | PECL | Set {{ package }} config (Ubuntu > 12.04)
  template:
    src={{ repository_basedir }}/php/templates/{{ package }}.ini.j2
    dest=/etc/php5/mods-available/{{ package }}.ini
    owner=root group=root mode=0644
  when: ${ansible_lsb.release} != "12.04"

- name: PHP | PECL | Set symbolic link to {{ package }} config (Ubuntu > 12.04)
  file:
    src=/etc/php5/mods-available/{{ package }}.ini
    dest=/etc/php5/conf.d/20-{{ package }}.ini
    owner=root group=root state=link
  when: ${ansible_lsb.release} != "12.04"

