---
# Part: PHP
# File: phpdev.yml
#
# Description: Install and configure PHP development packages from PEAR, PECL and other...
#
# Parameters:
#
# Dependencies ([part:]type:filename):
# - tasks:setup.yml
# - vars:main.yml (not necessary if you don't override defaults)
#
# OS familly: Ubuntu (>= 12.04)

- name: PHP | PHPDev | Install PHP development packages
  apt: pkg={{ item }} state=installed
  with_items:
    - php-pear

# PEAR Upgrade
# ####################
- name: PHP | PHPDev | Update pear packages
  command: pear upgrade

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

# Composer
# ######################
- name: PHP | PHPDev | Install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
