---

- hosts: local
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ../..

  tasks:
    - include: {{ repository_basedir }}/mongodb/tasks/setup.yml
    
  handlers:
    - include: {{ repository_basedir }}/mongodb/handlers/handlers.yml

