---

- hosts: webservers
  user: vagrant
  sudo: True

  vars:
    repository_basedir: ..
    php_xdebug_remote_host: '129.213.134.96'
    php_xdebug_remote_enable: 1

  tasks:
  - include: {{ repository_basedir }}/php/tasks/setup.yml
  - include: {{ repository_basedir }}/php/tasks/phpdev.yml
